### ISSUE TITLE
Vignettes must load sf

### ISSUE THREAD

**Issue by krlmlr** [mdsumner/ozmaps#6]
to be compatible with tibble 3.0.0.

Only then a `vec_proxy.sfc()` method is registered, which is now required so that sfc are recognized as vectors.

**Comment by mdsumner** [comment]
Oh god

**Comment by mdsumner** [comment]
... I can just remove the 'as_tibble', I think

**Comment by krlmlr** [comment]
Wouldn't that make the output in the vignette unnecessarily long?

I'd like to suggest to import sf instead, and make sure it's loaded when ozmaps loads (`#' @import sf` or `#@ importFrom sf sf`). This will ensure that all methods (not only `vec_proxy()`) are registered correctly for the objects you return. Imagine somebody applying dplyr workflows on ozmaps and getting different results depending on whether they load sf or not.

Do you have users that would *not* import sf anyway whenever they use ozmaps?

**Comment by mdsumner** [comment]
Yes definitely, me. I won't print the stuff in the vignette naively. But, the pressure to use sf is pretty relentless I might just give in and do it my way in another project.

Thanks!

**Comment by mdsumner** [comment]
Wouldn't it have been better for sf to add "list" to the sfc class?

**Comment by mdsumner** [comment]
Done now, thanks again. Congrats on 3.0.0 a massive chunk of work

**Comment by krlmlr** [comment]
Thanks.

Ideally sf would do that, yes:

``` r
class(sf::st_sfc(sf::st_point()))
#> [1] "sfc_POINT" "sfc"
```

<sup>Created on 2020-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

As a stop-gap, adding an explicit class to your object doesn't sound too bad to me.
